---
resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/chrisgreene/concourse1.git
    branch: master

jobs:
- name: concourse
  public: true
  plan:
  - get: concourse
  - task: hello-world
    file: concourse/configs/hello.yml
