--- 
resources:
- name: concourse1
  type: git
  source:
    uri: https://github.com/chrisgreene/concourse1.git
    branch: master
jobs:
- name: push-data
  plan: 
  - get: concourse1
    #trigger: true
  - task: update-file
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: busybox }
      inputs:
      - name: concourse1
      outputs:
      - name: results
      run: 
        path: concourse1/multi-job/update-file.sh
- name: get-data
  plan:
  - get: concourse1
    passed: [push-data]
    trigger: true
  - task: get-file
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: busybox }
      #inputs:
      #- name: results
      run: 
        path: ls  
        args: ['-ltR]'
