--- 
resources:
- name: concourse1
  type: git
  source:
    uri: https://github.com/chrisgreene/concourse1.git
    branch: master
jobs:
- name: job1
  plan: 
  - get: concourse1
    #trigger: true
  - task: task1
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: busybox }
      inputs:
      - name: concourse1
      run: 
        path: ls 
        args: ['-ltR']
- name: job2
  plan:
  - get: concourse1
    passed: [job1]
    trigger: true
  - task: task1
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: busybox }
      run: 
        path: ls
        args: ['-ltR']
